micronaut:
  application:
    name: ssp
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
#redis:
#  uri: ${REDIS_URL}